server:
  port: 10099
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10066/eureka
#    registry-fetch-interval-seconds: 10
#  instance:
#    prefer-ip-address: true #ip优先，获取host时会获取到ip地址
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${server.port} #在eureka中的实例id

zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    user-service: /user/** #将用户微服务映射到user
    auth-service: /auth/** #将授权中心映射到auth路径下
  add-host-header: true #携带hosy本身的请求头信息
  sensitive-headers:  #敏感头设置为null

#负载均衡的设置
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

#熔断机制
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长：10000ms

  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/send
      - /api/item
management:
  endpoints:
    web:
      exposure:
        include: "*"

domain:
  name: 127.0.0.1:8080

user:
  service:
    name: user-service