server:
  port: 10076
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lihui121/myconfig.git
          search-paths: myconfig
          username: 666666
          password: xxxxxx
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10066/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true #ip优先，获取host时会获取到ip地址
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #在eureka中的实例id

management:
  endpoints:
    web:
      exposure:
        include: "*"
